server:
  port: 5656
  servlet:
    context-path: /
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes: # 路由规则定义
        - id: product-service # 路由ID
          uri: http://localhost:8085/ # 路由地址
          predicates: # 断言规则
            - Path=/product/**


        - id: order-service # 路由ID
          uri: http://localhost:8090/ # 路由地址
          predicates: # 断言规则
            - Path=/order/**
          filters:
            - MyCustomer
            #配置的是网关(局部)拦截器的名字
            #- AddRequestParameter=info, hehe  #添加请求参数（属于前置过滤网关）
            #- RewritePath=/api-gateway(?<segment>/?.*), $\{segment} #将/api-gateway/product/请求重写成/product/请求（属于前置过滤网关）
            #- SetStatus=456 #无论哪种情况，响应的HTTP状态都设置为456（属于后置过滤网关）
            #- AddResponseHeader=X-Response-Author, java1234 #返回信息，添加header头信息（属于后置过滤网关）